name: Server Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use node.js 18.20.2 and npm 10.5.2
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.2'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Deploy
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo $SSH_PRIVATE_KEY | base64 -d > ssh-key
          chmod 400 ssh-key 
          ssh -i ssh-key -o StrictHostKeyChecking=no ${{secrets.SERVER_USER}}@${{secrets.SERVER_HOST}} "cd /var/www/guitarla && GIT_SSH_COMMAND='ssh -i /home/henry/.ssh/id_rsa' git pull origin master"
          npm install
          npm run build
          pm2 restart guitarla