name: Server Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use node.js 18.20.2 and npm 10.5.2
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.2'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SECRET_KEY }}
          script: |
            cd /var/www/guitarla
            git pull origin master
            ${{ secrets.NODE_BIN }}npm install
            ${{ secrets.NODE_BIN }}npm run build
            ${{ secrets.NODE_BIN }}pm2 restart guitarla
            
        
